### ISSUE TITLE
[Question] Does OnfidoSDK support Foldable Devices?

### ISSUE THREAD

**Issue by bkraszewski** [onfido/onfido-android-sdk#182]
#### What was the expected behaviour?
I wanted to ask if onfido SDK supports foldable devices like Samsung Z3 Fold
#### What happened instead?
App crashed
#### Version info:

- `onfido-capture-sdk` version:
11.3.0
- Android API version(s):
32
- `compileSdkVersion`:
- 32
- `targetSdkVersion`:
- 32
- `minSdkVersion`:
- 21
- Support library version (if applicable):

#### Steps to reproduce:
Launch onfido activity
#### Onfido Flow initialization code:
Crashed when asking to scan user passport
#### Other useful info:
_screenshots, videos, etc._

**Comment by onfido-website-team** [comment]
Hi @bkraszewski [bkraszewski](https://github.com/bkraszewski)
 
Sorry for the delay. We haven't heard about any issue related to foldable devices yet. 

In order to investigate this issue further, we will need more details of your integration, screenshots or videos. Could you please raise a ticket at [api@onfido.com](mailto:api@onfido.com) ?

Kind regards
