### ISSUE TITLE
SDK uses 'unsafe' encryption patterns via org.jmrtd.protocol.PACEProtocol.pseudoRandomFunction

### ISSUE THREAD

**Issue by leewapadmi** [onfido/onfido-android-sdk#217]
#### What was the expected behaviour?
The SDK shouldn't use encryption patterns determined to be unsafe.

#### What happened instead?
When uploading our app to Google Play, we get a warning telling us that the app "contains unsafe cryptographic encryption patterns", referencing the library function `org.jmrtd.protocol.PACEProtocol.pseudoRandomFunction` used by the Onfido beta NFC functionality.

#### Version info:
11.5.0

- `onfido-capture-sdk` version: 11.5.0
- Android API version(s):

- `compileSdkVersion`: 31
- `targetSdkVersion`: 30
- `minSdkVersion`: 26
- Support library version (if applicable):

#### Steps to reproduce:
Enable Onfido NFC functionality in code, then upload app to Play Store

#### Issue severity information (number of users/crashes if applicable):
Low severity, as this is only a warning

#### Other useful info:
_screenshots, videos, etc._

**Comment by gurpreet-onfido** [comment]
Hello @leewapadmi Thank you for bringing this up. We will discuss this internally with our team and will get back to you as soon as we can.

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello Lee,

Greetings for the day!

The root cause is relating to an issue with the 3rd party library used currently for NFC on Android (jmrtd). This means that there is no way for us to address this in the short term. We are currently in the process of updating some of those libraries for the next version of our NFC component and we will be able to confirm shortly if the issue is addressed there.

We will keep you posted.

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello @leewapadmi 

Greetings for the day!

Our team has mentioned that the warning and underlying cause are still present in the latest version of the underlying open-source jmrtd library. Onfido will continue checking subsequent versions for a resolution but there is no plan to replace/override this core function.

Please let us know if there is anything else we can help you with.

Kind regards
Gurpreet Singh
